pipeline {
    agent any
    stages {
        stage("Code Checkout from Git") {
            steps { 
                checkout([$class: 'GitSCM', branches: [[name: '*/develop']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/p-nishad/Jenkins-workshop']]])
            }
        }
        stage("Code Quality Check") {
            steps {
                dir('maven') { 
                withSonarQubeEnv(installationName : 'my-sonarcloud', credentialsId : 'sonar-token') {
                    sh "mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=timp"
                    }
                }
            }
        }
        stage("Security Scan") {
            steps {
                echo("scan")
            }
        }
        stage("Build") {
            steps {
                echo("Build")
            }
        }
        stage("Deploy") {
            steps {
                echo("deploy")
            }
        }
        stage("Send Notification") {
            steps {
                echo("slack")
                }
            }
        }
    }
}