pipeline {
    agent any
    tools { go 'go-1.19' }

    environment {
        ENV = "${env.BRANCH_NAME == 'main' ? 'PROD' : 'DEV'}"
        BRANCH = "${env.BRANCH_NAME}" // This is for deploy
    }

    stages {
        stage("Send initial Notification") {
            when {
                anyOf {
                    branch 'main';
                    branch 'develop'
                }
            }
            steps {
                slackSend channel: '#general',
                        message: "Build fo job ${env.JOB_NAME} has started - (<${env.BUILD_URL}|Open>)"
            }
        }
        stage("Build") {
            steps {
                sh 'bash Go/scripts/build.sh' //Run the build.sh
                }
        }
    
        stage("Test") {
            steps {
                sh 'bash Go/scripts/test.sh'  // Run the test.sh
            }
        }
        stage("Deploy") {
            when {
                anyOf {
                    branch 'main';
                    branch 'develop'

                }
            }
            steps {
                sh 'export JENKINS_NODE_COOKIE=do_not_kill ; bash Go/scripts/deploy.sh'
            }
        }
    }
    post {
        always {
            slackSend channel: '#general',
                    color: "${currentBuild.currentResult == 'SUCCESS' ? 'good' : 'danger'}",
                    message: "Build for job ${env.JOB_NAME} finished with status ${currentBuild.currentResult} - (<${env.BUILD_URL}|Open>)"
        }
    }
}